### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by rlivsey** [brzpegasus/ember-cli-node-webkit#1]
Looks like a great addon, can't wait to give it a go. 

It doesn't appear to have been published to npm yet?

```
$ npm install --save-dev ember-cli-node-webkit
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save-dev" "ember-cli-node-webkit"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code E404

npm ERR! 404 Not Found: ember-cli-node-webkit
```

**Comment by itsthatguy** [comment]
+1

**Comment by brzpegasus** [comment]
It was announced before I got around to publishing it, but it is published now: https://www.npmjs.com/package/ember-cli-node-webkit :)

**Comment by rlivsey** [comment]
@brzpegasus I thought that might have been the case! Thanks for pushing it up to NPM, I'll have a play tomorrow. Cheers.
