### ISSUE TITLE
doesn't play well with ember-cli-dotenv when creating a package

### ISSUE THREAD

**Issue by nadeemkhedr** [brzpegasus/ember-cli-node-webkit#11]
in OSX

the plugin `ember-cli-dotenv`  is used for putting env variables in a separate `.env` file and it will get injected in the `index.html` in a `meta` tag and you can access it in the app

The problem is when I do `ember nw` it works well, it reads the env variables, but when i do `ember nw:package`, it doesn't work. The variables from `ember-cli-dotenv` are not injected

I inspected the `index.html` in the  package, it doesn't contain the values there

**Comment by brzpegasus** [comment]
Thanks for reporting! I will take a look later today.

**Comment by brzpegasus** [comment]
I just tried this out but it seems to be working fine. By default, `ember nw:package` will build your app for production. Are you exposing the variable for all environments, or only development?

Here was the configuration that I tested with:

```
// .env
NW_DEBUG=true
```

```javascript
// config/environment.js
module.exports = function(environment) {
  var ENV = {
    NW_DEBUG: process.env.NW_DEBUG,
    // ...
  };

  return ENV;
}
```

The compiled `dist/index.html` after `ember nw:package` does contain `NW_DEBUG=true`:

```html
<html>
  <head>
  <meta name="ember-nw-markdown/config/environment" content="%7B%22NW_DEBUG%22%3A%22true%22%2C..." />
  ...
  </head>
  ...
</html>
```

**Comment by nadeemkhedr** [comment]
your actually totally right, in the `environment.js` for some reason, i am doing if production and reseting the value, thanks for the help
