### ISSUE TITLE
Current process to install is not documented, or straight forward

### ISSUE THREAD

**Issue by itsthatguy** [brzpegasus/ember-cli-node-webkit#2]
Here is a gist that outlines the required steps to install, as it currently exists:

https://gist.github.com/itsthatguy/9f488523809507e70ee1

**Comment by brzpegasus** [comment]
Thanks for the detailed steps! With the addon now on NPM, it should be much simpler. I'll document these steps, however, for those who wish to install directly from source.

**Comment by itsthatguy** [comment]
Awesome. I'll test when I get home. Given updated docs and  `npm install ember-cli-node-webkit ` works, this should be good to close!

:+1: thanks for the follow up @brzpegasus

**Comment by brzpegasus** [comment]
I've incorporated the steps to install the addon from the git repo to the end of the README. Thanks for checking this out!
