### ISSUE TITLE
Error downloading node webkit

### ISSUE THREAD

**Issue by Artmann** [brzpegasus/ember-cli-node-webkit#26]
Running
<code>ember nw:package -prod</code>
generates
<code>
Downloading: http://dl.nwjs.io/v0.13.0/nwjs-v0.13.0-linux-x64.tar.gz
ERROR: The version 0.13.0 does not have a corresponding build posted at http://dl.node-webkit.org/.    Please choose a version from that list
</code>

It's seems that 0.13.0 is not a valid version and this problem can be solved by specifying the version in nw-package.js
<code>version: '0.12.2'</code>

**Comment by brzpegasus** [comment]
Sorry for the delay. I've updated the version of `node-webkit-builder`, which has a [fix](https://github.com/mllrsohn/node-webkit-builder/commit/121c185f44bbcc30570edb25a1b713335a9e4f73) for this issue.

It'll get published shortly.
