### ISSUE TITLE
node-webkit-builder is deprecated

### ISSUE THREAD

**Issue by jonblack** [brzpegasus/ember-cli-node-webkit#33]
I get the following warning when installing ember-cli-node-webkit:

> npm WARN deprecated node-webkit-builder@1.0.13: WARNING: This module has been renamed to nw-builder. Install using nw-builder instead, node-webkit-builder will no longer be updated.

Perhaps it's also a good idea to rename this project to `ember-cli-nw` as well?

**Comment by brzpegasus** [comment]
I almost did rename it! Until I discovered there was already a package on NPM called [`ember-cli-nw`](https://www.npmjs.com/package/ember-cli-nw). But I can't track down its source on GitHub, and the project is very bare. At any rate, it seems that I am stuck with the `node-webkit` name given the conflict.

I can update the `node-webkit-builder` dependency to `nw-builder` though. =)

**Comment by jonblack** [comment]
@olivierlesnicki, according to npmjs.org you're the creator of ember-cli-nw. Did you have plans for that project?

**Comment by brzpegasus** [comment]
@jonblack This project is now named `ember-cli-nwjs`. I've updated it to use the `nw-builder` package as well.

**Comment by jonblack** [comment]
That also works. Great!
