### ISSUE TITLE
`ember nw` crashes before starting nw.js

### ISSUE THREAD

**Issue by AKST** [brzpegasus/ember-cli-node-webkit#4]
Every time I run `ember nw`, it builds the nw app, but then it crashes just before starting `nw.js`. However I can run `nw` in the same project and the `nw` application will start. Here is the output from ember-cli

```
version: 0.1.5
Build successful - 7313ms.

Slowest Trees                  | Total
-------------------------------+----------------
CoffeeScriptFilter             | 2251ms
EsnextFilter                   | 1789ms
EsnextFilter                   | 468ms
ES6Modules                     | 411ms

Starting nw.js...
Error running nw.js
spawn ENOENT
Error: spawn ENOENT
  at errnoException (child_process.js:1011:11)
  at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by AKST** [comment]
I'm running `OS X`, and I have installed node webkit via `npm`, [this line maybe the culprit](https://github.com/brzpegasus/ember-cli-node-webkit/blob/master/lib/commands/nw.js#L50)? I'm not sure it's reasonable to assume people on `OS X` have installed `nw.js` as a application, but at the very least it should be worth while to provide an error message indicating that they should set a environment variable to indicate the location of `nw` in the event of the child process crashing.

**Comment by brzpegasus** [comment]
Thanks for reporting this! I'll work on a fix to handle this more graciously and publish a new version soon. Hopefully, you're still able to get things running in the meantime with the `NW_PATH` setting.

**Comment by AKST** [comment]
No worries! Yeah I saw the NW_PATH when digging through the source.

**Comment by brzpegasus** [comment]
I've updated the addon to add NW.js as a local NPM package in your project when you first install the addon with `ember install:addon ember-cli-node-webkit`.

`ember nw` will now look for the `nw` binary in the project's local dependencies first, then search for the `NW_PATH` environment variable next, and finally fallback to running plain vanilla `nw`. If none of those works, an error message on how to configure the NW.js binary is shown:

```
Starting nw.js...

Error running the following command: nw

Either re-run the blueprint with 'ember g node-webkit' to add NW.js as an NPM dependency in your project,
or set an environment variable named 'NW_PATH' pointing to your NW.js binary.
```

You can read more about the changes [here](https://github.com/brzpegasus/ember-cli-node-webkit/releases/tag/v0.1.3).
